### ISSUE TITLE
Reg account at https://devfolio.co/onchain-summer/dashboard

### ISSUE THREAD

**Issue by CindyNFT** [CharityConn/CharityConnect#1]
Reg account at https://devfolio.co/onchain-summer/dashboard #1
Use INVITE CODE 557490e97a to join CharityConnect team

- [x] @CindyNFT 
- [x] @hboon 
- [ ] @huweihong
- [x] @JustinFeng

**Comment by hboon** [comment]
@CindyNFT have registered account. Can't find how/where to enter invite code.

**Comment by CindyNFT** [comment]
> @CindyNFT have registered account. Can't find how/where to enter invite code.

https://devfolio.co/onchain-summer/dashboard

**Comment by hboon** [comment]
@CindyNFT does @huweihong still need to register?

**Comment by CindyNFT** [comment]
> @CindyNFT does @huweihong still need to register?

don't need
