### ISSUE TITLE
a few text changes 

### ISSUE THREAD

**Issue by zhangzhongnan928** [CharityConn/CharityConnect#14]
<img width="762" alt="Screenshot 2024-09-11 at 6 57 37 PM" src="https://github.com/user-attachments/assets/95bda3d3-7a56-4435-a01e-bc829d2348cd">
<img width="688" alt="Screenshot 2024-09-11 at 7 01 14 PM" src="https://github.com/user-attachments/assets/acc4cfe7-0215-40d0-aafb-be0aabdedb47">

**Comment by hboon** [comment]
Done
