### ISSUE TITLE
Change "Vote for Charity Fund Allocation" to "Governance"

### ISSUE THREAD

**Issue by zhangzhongnan928** [CharityConn/CharityConnect#17]
<img width="491" alt="Screenshot 2024-09-13 at 9 05 50 AM" src="https://github.com/user-attachments/assets/d0f91ee6-6a97-4bfd-a465-dde483a1ed93">

Text change "Vote for Charity Fund Allocation" to "Governance"

**Comment by hboon** [comment]
Done
