### ISSUE TITLE
Move the project to charityconnect.io 

### ISSUE THREAD

**Issue by CindyNFT** [CharityConn/CharityConnect#3]
- [x] Host this service on AWS @JustinFeng 
- [x] @zhangzhongnan928  invite @JustinFeng and Feng to GoDaddy for managing charityconnect.io 
- [x] Move the project to charityconnect.io

**Comment by zhangzhongnan928** [comment]
> Hi @CindyNFT it's already hosted on AWS during the Hackthon, I will take a look at the DNS set up once I got the access to charityconnect.io on GoDaddy

added jia@smarttokenlabs.com to godaddy

**Comment by zhangzhongnan928** [comment]
sent again

**Comment by CindyNFT** [comment]
https://charityconnect.io/ goes to https://charityconnect.io/lander @JustinFeng
